import { useState, useRef, useEffect, useMemo } from "react";

const PROFESSIONS = [
  "3D Modeler",
  "Accountant",
  "Acupuncturist",
  "Aerospace Engineer",
  "Agricultural Inspector",
  "Air Conditioning Technician",
  "Appliance Installer",
  "Appliance Repair",
  "Architect",
  "Archivist",
  "Artist",
  "Asbestos Inspector",
  "Automotive Body Painter",
  "Automotive Mechanic",
  "Automotive Technician",
  "Baker",
  "Banquet Server",
  "Barista",
  "Barber",
  "Bartender",
  "Basement Finishing Specialist",
  "Battery Technician",
  "Behavioral Therapist",
  "Bicycle Repair Technician",
  "Biologist",
  "Biochemist",
  "Biohazard Cleanup Specialist",
  "Biomedical Engineer",
  "Biostatistician",
  "Blinds Installer",
  "Boat Mechanic",
  "Bookkeeper",
  "Bowling Alley Attendant",
  "Box Maker",
  "Bricklayer",
  "Broadcast Engineer",
  "Broadcast Technician",
  "Broker",
  "Brush Painter",
  "Building Inspector",
  "Building Maintenance Worker",
  "Builder",
  "Bus Driver",
  "Butcher",
  "Cabinet Maker",
  "Cake Decorator",
  "Camerman",
  "Candidate Care",
  "Carpenter",
  "Carpet Cleaner",
  "Carpet Installer",
  "Cartographer",
  "Cashier",
  "Catering Assistant",
  "Caterer",
  "Ceiling Installer",
  "Chef",
  "Childcare Provider",
  "Chimney Sweep",
  "Civil Engineer",
  "Clergy",
  "Clerk",
  "Climate Consultant",
  "Clothing Manufacturer",
  "Coiffure",
  "Commercial Driver",
  "Commercial Electrician",
  "Commercial Photographer",
  "Commercial Plumber",
  "Commissioner",
  "Communications Specialist",
  "Community Health Worker",
  "Compressor Operator",
  "Concrete Finisher",
  "Construction Foreman",
  "Construction Inspector",
  "Construction Manager",
  "Construction Worker",
  "Conservator",
  "Content Writer",
  "Contractor",
  "Cook",
  "Copy Editor",
  "Copywriter",
  "Cost Estimator",
  "Cotton Picker",
  "Counter Worker",
  "Courier",
  "Custodian",
  "Dancer",
  "Data Entry Clerk",
  "Data Scientist",
  "Deck Builder",
  "Deckhand",
  "Decorator",
  "Defensive Driving Instructor",
  "Delivery Driver",
  "Demolition Worker",
  "Dental Assistant",
  "Dental Hygienist",
  "Dentist",
  "Diesel Mechanic",
  "Dietitian",
  "Digital Artist",
  "Digital Content Creator",
  "Digital Marketer",
  "Director",
  "Disability Support Worker",
  "Dispatch Clerk",
  "Disney Imagineer",
  "DJ",
  "Doctor",
  "Document Controller",
  "Dog Groomer",
  "Dog Walker",
  "Drainage Engineer",
  "Drywall Installer",
  "Drywall Parker",
  "Dump Truck Driver",
  "Dust Control Operator",
  "Dyer",
  "Editor",
  "Education Administrator",
  "Educational Psychologist",
  "Electrician",
  "Elevator Installer",
  "Engineer",
  "Engineering Technician",
  "Entertainment Attendant",
  "Equipment Operator",
  "Estate Agent",
  "Event Coordinator",
  "Event Planner",
  "Event Promoter",
  "Executive Assistant",
  "Executive Chef",
  "Executive Producer",
  "Expediter",
  "Farmer",
  "Farmworker",
  "Fashion Designer",
  "Fastener Specialist",
  "Fence Builder",
  "Fencer",
  "Festival Coordinator",
  "Firefighter",
  "Fish Cooker",
  "Fish Hatchery Manager",
  "Fishing Guide",
  "Fitter",
  "Fixer",
  "Flagger",
  "Florist",
  "Fly Ash Operator",
  "Food Inspector",
  "Food Scientist",
  "Forklift Operator",
  "Framing Carpenter",
  "Freezer Technician",
  "Furrier",
  "Game Developer",
  "Game Warden",
  "Gas Plant Operator",
  "Gas Technician",
  "General Contractor",
  "General Manager",
  "Generator Technician",
  "Geologist",
  "Glass Installer",
  "Glazier",
  "Goldsmith",
  "Goldworker",
  "Graduate Assistant",
  "Graduate Teacher",
  "Grant Writer",
  "Graphic Artist",
  "Graphic Designer",
  "Groundskeeper",
  "Guitar Maker",
  "Hairdresser",
  "Hair Stylist",
  "Handyman",
  "Haul Truck Driver",
  "Haute Couture Designer",
  "Hazardous Material Inspector",
  "Health Aide",
  "Health Care Aide",
  "Health Care Assistant",
  "Health Information Technician",
  "Hearse Driver",
  "Heat Treating Operator",
  "Helicopter Pilot",
  "Herbalist",
  "High School Teacher",
  "Hippotherapist",
  "Historic Preservationist",
  "Home Care Aide",
  "Home Inspector",
  "Home Stager",
  "Homemaker",
  "Honor Guard",
  "Host / Hostess",
  "Hot Water Technician",
  "House Cleaner",
  "House Sitter",
  "HVAC Contractor",
  "HVAC Technician",
  "Hydraulic Engineer",
  "Hydraulic Installer",
  "ICT Teacher",
  "Ice Cream Maker",
  "Ice Machine Technician",
  "Illustrator",
  "Immigration Consultant",
  "Importer",
  "Industrial Engineer",
  "Industrial Photographer",
  "Industrial Technician",
  "Information Technology Manager",
  "Inmate Counselor",
  "Instrument Technician",
  "Insurance Adjuster",
  "Insurance Agent",
  "Interior Designer",
  "International Business Agent",
  "Interpreter",
  "Interpreter for the Deaf",
  "Investment Analyst",
  "Investment Banker",
  "Irrigation Installer",
  "Irrigator",
  "IT Consultant",
  "IT Coordinator",
  "IT Manager",
  "Janitor",
  "Jazz Musician",
  "Jeweler",
  "Jewelry Designer",
  "Jingle Writer",
  "Journeyman",
  "Justice of the Peace",
  "Juvenile Counselor",
  "Kaizen Consultant",
  "Karaoke Host",
  "Kayak Guide",
  "Keynote Speaker",
  "Kidney Dialysis Technician",
  "Kinesiologist",
  "Kitchen Helper",
  "Kitchen Porter",
  "Knife Grinder",
  "Laboratory Assistant",
  "Laboratory Technician",
  "Land Developer",
  "Land Economist",
  "Landfill Operator",
  "Landlord",
  "Landscape Architect",
  "Landscape Designer",
  "Landscaper",
  "Laser Operator",
  "Laundry Worker",
  "Law Clerk",
  "Lawyer",
  "Layout Worker",
  "Lawn Care Worker",
  "Lawn Mower Repair Person",
  "Leather Worker",
  "Legal Assistant",
  "Librarian",
  "License Bureau Agent",
  "License Inspector",
  "Lie Detector Technician",
  "Life Coach",
  "Lift Truck Driver",
  "Lighting Designer",
  "Lighting Installer",
  "Lineman",
  "Linguist",
  "Lion Tamer",
  "Listings Clerk",
  "Literacy Tutor",
  "Locomotive Engineer",
  "Locksmith",
  "Log Truck Driver",
  "Logistics Coordinator",
  "Logistics Manager",
  "Landscape Maintenance",
  "Lounge Singer",
  "Lumberjack",
  "Machine Operator",
  "Machinist",
  "Mail Carrier",
  "Maintenance Worker",
  "Maid",
  "Makeup Artist",
  "Manager",
  "Mango Inspector",
  "Manicurist",
  "Mason",
  "Marine Engineer",
  "Marine Surveyor",
  "Marriage and Family Therapist",
  "Master Electrician",
  "Master Mechanic",
  "Master Plumber",
  "Master Welder",
  "Mathematician",
  "Maturation Technician",
  "Meat Inspector",
  "Meat Processor",
  "Medical Coder",
  "Medical Record Technician",
  "Medical Representative",
  "Medical Secretary",
  "Medical Transcriptionist",
  "Medicare Counselor",
  "Mental Health Counselor",
  "Mental Health Technician",
  "Merchandiser",
  "Metal Fabricator",
  "Metal Worker",
  "Meteorologist",
  "Meter Reader",
  "Microbiologist",
  "Military Officer",
  "Millwright",
  "Miner",
  "Ministry Associate",
  "Minister",
  "Mint Worker",
  "Missile Technician",
  "Mobile Mechanic",
  "Mobile Notary",
  "Mobile Home Installer",
  "Model",
  "Model Builder",
  "Molecular Biologist",
  "Mortician",
  "Mortgage Broker",
  "Mortgage Loan Officer",
  "Morgue Technician",
  "Motorcycle Mechanic",
  "Motorcycle Rider",
  "Motorboat Operator",
  "Mountaineer",
  "Mover",
  "Moving Helper",
  "Mower",
  "Mural Painter",
  "Museum Curator",
  "Museum Guide",
  "Music Director",
  "Musician",
  "Nail Technician",
  "Nanny",
  "Narrator",
  "Neurologist",
  "New Media Artist",
  "Newspaper Carrier",
  "Nursery Worker",
  "Nurse",
  "Nursing Assistant",
  "Nuclear Engineer",
  "Nuclear Technician",
  "Nutritionist",
  "Nursery Worker",
  "Office Clerk",
  "Office Coordinator",
  "Oil Driller",
  "Oil Field Worker",
  "Oil Change Technician",
  "Online Tutor",
  "Opthalmologist",
  "Optician",
  "Optometrist",
  "Orchard Worker",
  "Order Picker",
  "Orderly",
  "Organ Builder",
  "Organist",
  "Orienteering Guide",
  "Ornithologist",
  "Outreach Worker",
  "Package Handler",
  "Packer",
  "Packing Crew Worker",
  "Pallet Jack Operator",
  "Palm Reader",
  "Panning Operator",
  "Paperhanger",
  "Parcel Delivery Driver",
  "Parcels Supervisor",
  "Parking Attendant",
  "Parking Enforcement Officer",
  "Parking Lot Attendant",
  "Part-Time Clerk",
  "Pastor",
  "Pathologist",
  "Patient Care Technician",
  "Patient Transporter",
  "Pattern Maker",
  "Payroll Clerk",
  "Peace Officer",
  "Pediatrician",
  "Pedicure Technician",
  "Penman",
  "Painter",
  "Personal Assistant",
  "Personal Chef",
  "Personal Trainer",
  "Pet Groomer",
  "Pet Sitter",
  "Pharmacist",
  "Pharmacy Technician",
  "Phlebotomist",
  "Photographer",
  "Photography Assistant",
  "Photolithographer",
  "Piano Tuner",
  "Picture Framer",
  "Pile Driver Operator",
  "Pilates Instructor",
  "Pipe Fitting Installer",
  "Pipe Layer",
  "Pipe Turner",
  "Pitcher",
  "Plastic Surgeon",
  "Plastic Worker",
  "Plasterer",
  "Plate Maker",
  "Plumber",
  "Plumbing Inspector",
  "Plumbing Technician",
  "Plumber's Helper",
  "Plumber's Apprentice",
  "Poker Dealer",
  "Police Officer",
  "Politician",
  "Pool Attendant",
  "Pool Builder",
  "Pool Cleaner",
  "Pool Maintenance Worker",
  "Pool Operator",
  "Porter",
  "Postal Carrier",
  "Postal Clerk",
  "Postal Worker",
  "Postman",
  "Potter",
  "Poultry Farmer",
  "Poultry Worker",
  "Power Plant Operator",
  "Powerline Worker",
  "Precious Metal Worker",
  "Preset Engineer",
  "Prevention Specialist",
  "Primary School Teacher",
  "Printer Operator",
  "Prison Guard",
  "Prison Warden",
  "Private Detective",
  "Private Duty Nurse",
  "Private Pilot",
  "Private School Teacher",
  "Private Security Officer",
  "Probation Officer",
  "Process Engineer",
  "Producer",
  "Professor",
  "Program Coordinator",
  "Project Coordinator",
  "Project Manager",
  "Promoter",
  "Prosthetist",
  "Protective Service Officer",
  "Provider",
  "Psychiatrist",
  "Psychologist",
  "Psychometrist",
  "Psychotherapist",
  "Public Relations Manager",
  "Public Relations Specialist",
  "Public Relations Writer",
  "Public Safety Officer",
  "Public Service Dispatcher",
  "Pump Operator",
  "Purchasing Agent",
  "Purchasing Assistant",
  "Purchasing Buyer",
  "Purchasing Clerk",
  "Purchasing Manager",
  "Radiographer",
  "Radiologic Technologist",
  "Radiation Therapist",
  "Radio Announcer",
  "Radio Engineer",
  "Radio Technician",
  "Radio Operator",
  "Radio Person",
  "Radiologist",
  "Railroad Conductor",
  "Railroad Engineer",
  "Railroad Worker",
  "Rancher",
  "Range Manager",
  "Real Estate Appraiser",
  "Real Estate Agent",
  "Real Estate Assistant",
  "Real Estate Broker",
  "Real Estate Developer",
  "Real Estate Inspector",
  "Real Estate Manager",
  "Receptionist",
  "Reefer Operator",
  "Referee",
  "Refrigerator Technician",
  "Refrigeration Mechanic",
  "Regional Manager",
  "Register Operator",
  "Rehabilitation Counselor",
  "Reinsurance Analyst",
  "Relations Officer",
  "Research Assistant",
  "Research Associate",
  "Research Fellow",
  "Research Scientist",
  "Respiratory Therapist",
  "Restaurant Manager",
  "Restaurant Worker",
  "Retail Clerk",
  "Retail Manager",
  "Retail Salesperson",
  "Reverend",
  "Rigger",
  "Risk Analyst",
  "Risk Manager",
  "Road Builder",
  "Road Crew Worker",
  "Road Inspector",
  "Road Maintenance Worker",
  "Road Worker",
  "Robotics Engineer",
  "Roof Inspector",
  "Roofer",
  "Room Attendant",
  "Route Driver",
  "Route Manager",
  "Route Salesperson",
  "Route Supervisor",
  "Roustabout",
  "Rowing Coach",
  "RN",
  "Roofer's Helper",
  "Room Sorter",
  "Ropemaker",
  "Roustabout",
  "Ruby Worker",
  "Rural Carrier",
  "Safety Engineer",
  "Safety Inspector",
  "Safety Officer",
  "Sales Agent",
  "Sales Associate",
  "Sales Clerk",
  "Sales Manager",
  "Sales Representative",
  "Saleswoman",
  "Sandwich Artist",
  "Satellite Engineer",
  "Satisfier",
  "Savings Officer",
  "Scaler",
  "Scenic Designer",
  "School Bus Driver",
  "School Counselor",
  "School Janitor",
  "School Nurse",
  "School Psychologist",
  "School Secretary",
  "School Teacher",
  "Scientific Glassblower",
  "Scientific Officer",
  "Scrap Metal Worker",
  "Screen Printer",
  "Scrub Nurse",
  "Security Guard",
  "Security Officer",
  "Security Specialist",
  "Septic Tank Cleaner",
  "Serif Designer",
  "Server",
  "Sewing Machine Operator",
  "Sewing Instructor",
  "Shipper",
  "Shipping Clerk",
  "Shipping Coordinator",
  "Shipping Manager",
  "Shoemaker",
  "Shorthand Reporter",
  "Shower Attendant",
  "Signal & Telecommunications Worker",
  "Sign Painter",
  "Signmaker",
  "Silversmith",
  "Simultaneous Interpreter",
  "Singer",
  "Site Safety Officer",
  "Site Supervisor",
  "Ski Instructor",
  "Skilled Nursing Facility Nurse",
  "Skin Care Specialist",
  "Ski Patrol",
  "Skilled Nursing Assistant",
  "Skilled Nursing Worker",
  "Slaughterer",
  "Sleep Technician",
  "Slimming Consultant",
  "Small Engine Mechanic",
  "Smart Home Installer",
  "Smelter",
  "Social Media Manager",
  "Social Media Specialist",
  "Social Work Assistant",
  "Social Worker",
  "Soda Jerk",
  "Solicitor",
  "Sous Chef",
  "Spatial Designer",
  "Spanish Teacher",
  "Special Events Planner",
  "Special Education Teacher",
  "Speech Therapist",
  "Spice Grinder",
  "Spiritual Director",
  "Spotter",
  "Spread Operator",
  "Spring Maker",
  "Spy",
  "Square Dance Caller",
  "Stage Director",
  "Stage Manager",
  "Stair Builder",
  "Stenographer",
  "Stepfamily Counselor",
  "Stock Clerk",
  "Stock Handler",
  "Stock Loader",
  "Stock Manager",
  "Stockbroker",
  "Storage Technician",
  "Stove Repairman",
  "Subcontractor",
  "Subway Operator",
  "Sculptor",
  "Survey Assistant",
  "Surveyor",
  "Survival Specialist",
  "Survivalist",
  "Surgical Nurse",
  "Surgical Technician",
  "Surgical Assistant",
  "Surgeon",
  "Surveyor",
  "Survivalist",
  "Sushi Chef",
  "Surveillance Officer",
  "Surplus Store Manager",
  "Swami",
  "Swimming Coach",
  "Swimming Instructor",
  "Swimmer",
  "Sympathetic Magic Practitioner",
  "Syndicated Columnist",
  "Systems Administrator",
  "Systems Analyst",
  "Systems Engineer",
  "Systems Manager",
  "Systems Scientist",
  "Systems Specialist",
  "Systems Technician",
  "Systems Tester",
  "Systems User",
  "Systems Vendor",
  "Systems Worker",
  "Systems Writer",
  "Tabla Maker",
  "Tailor",
  "Talent Acquirer",
  "Talent Agent",
  "Talent Coordinator",
  "Talent Developer",
  "Talent Director",
  "Talent Manager",
  "Talent Scout",
  "Talent Searcher",
  "Talent Seeker",
  "Talent Sponsor",
  "Talent Sourcer",
  "Tax Preparer",
  "Taxi Driver",
  "Taxidermist",
  "Tea Blender",
  "Teacher",
  "Teacher Assistant",
  "Teamster",
  "Technical Director",
  "Technical Editor",
  "Technical Engineer",
  "Technical Writer",
  "Technician",
  "Teller",
  "Tennis Instructor",
  "Tent Maker",
  "Theatrical Technician",
  "Therapist",
  "Thesis Advisor",
  "Tiler",
  "Timer",
  "Tissue Processor",
  "Toastmaster",
  "Tobacco Sorter",
  "Tool Grinder",
  "Tool Inspector",
  "Toolmaker",
  "Tour Guide",
  "Tourist Guide",
  "Tow Truck Driver",
  "Tow Driver",
  "Tracker",
  "Traffic Director",
  "Traffic Engineer",
  "Traffic Officer",
  "Traffic Signal Technician",
  "Traffic Surveyor",
  "Traffic Technician",
  "Traffic Warden",
  "Train Attendant",
  "Train Driver",
  "Train Engineer",
  "Train Conductor",
  "Trainer",
  "Transit Driver",
  "Transit Inspector",
  "Transit Officer",
  "Transit Planner",
  "Transit Scheduler",
  "Transit Supervisor",
  "Translator",
  "Transport Driver",
  "Transport Manager",
  "Transport Operator",
  "Transportation Analyst",
  "Transportation Coordinator",
  "Transportation Director",
  "Transportation Engineer",
  "Transportation Manager",
  "Transportation Planner",
  "Transportation Supervisor",
  "Trapper",
  "Travel Agent",
  "Travel Consultant",
  "Travel Guide",
  "Travel Writer",
  "Triage Nurse",
  "Trick Artist",
  "Trimmer",
  "Truck Driver",
  "Truck Mechanic",
  "Trucking Dispatcher",
  "Trucking Manager",
  "Trucking Owner",
  "Tub Tile Installer",
  "Turner",
  "Tutor",
  "Typewriter Repair Person",
  "Typist",
  "Upholsterer",
  "Umpire",
  "Uniform Distribution Coordinator",
  "University Administrator",
  "University Professor",
  "Unpacker",
  "Upholstery Worker",
  "Usher",
  "Urologist",
  "Valet",
  "Valet Parking Attendant",
  "Van Driver",
  "Veteran Service Officer",
  "Veterinarian",
  "Veterinary Assistant",
  "Veterinary Technician",
  "Veterinary Nurse",
  "Video Editor",
  "Video Game Designer",
  "Video Game Developer",
  "Video Producer",
  "Video Tape Duplicator",
  "Videographer",
  "Village Administrator",
  "Vintner",
  "Violin Maker",
  "Vision Therapist",
  "Visual Artist",
  "Visual Designer",
  "Vocational Nurse",
  "Vocational Rehabilitation Counselor",
  "Volleyball Coach",
  "Volunteer",
  "Vulnerability Assessment Analyst",
  "Vulcanizer",
  "Waiter",
  "Waitress",
  "Wall Paper Installer",
  "Warehouse Associate",
  "Warehouse Clerk",
  "Warehouse Coordinator",
  "Warehouse Manager",
  "Warehouse Worker",
  "Wardrobe Assistant",
  "Waste Management Worker",
  "Water Driller",
  "Water Meter Reader",
  "Water Plant Operator",
  "Water Treatment Plant Operator",
  "Waterfront Worker",
  "Weather Forecasting Assistant",
  "Weather Observer",
  "Wedding Planner",
  "Weightlifting Coach",
  "Well Driller",
  "Welder",
  "Welding Engineer",
  "Welding Inspector",
  "Welding Technician",
  "Welder's Helper",
  "Welfare Officer",
  "Wig Maker",
  "Window Cleaner",
  "Window Dresser",
  "Window Installer",
  "Wine Steward",
  "Wing Commander",
  "Winkler",
  "Wipe Operator",
  "Wireless Network Technician",
  "Wireless Technician",
  "Woman Doctor",
  "Word Processing Operator",
  "Work Coach",
  "Work Comp Clerk",
  "Work Comp Nurse",
  "Work From Home Agent",
  "Workplace Safety Officer",
  "Writer",
  "X-Ray Technician",
  "Xenobiologist",
  "Yacht Broker",
  "Yacht Captain",
  "Yacht Crew Member",
  "Yard Master",
  "Yarn Maker",
  "Yoga Instructor",
  "Youth Counselor",
  "Youth Leader",
  "Zebra Trainer",
  "Zoo Curator",
  "Zookeeper",
  "Zoologist",
  "Zoom Operator",
];

export default function ProfessionSelector({ value = [], onChange, placeholder = "Type or select a profession..." }) {
  const [query, setQuery] = useState("");
  const [isOpen, setIsOpen] = useState(false);
  const containerRef = useRef(null);

  const suggestions = useMemo(() => {
    const q = query.trim().toLowerCase();
    let results;
    if (!q) {
      results = PROFESSIONS.filter((p) => !value.includes(p));
    } else {
      results = PROFESSIONS.filter(
        (p) => p.toLowerCase().includes(q) && !value.includes(p)
      );
    }
    if (q && !value.includes(q.charAt(0).toUpperCase() + q.slice(1)) && !value.includes(q)) {
      const custom = q.charAt(0).toUpperCase() + q.slice(1);
      if (!results.includes(custom)) results.unshift(custom);
    }
    return results;
  }, [query, value]);

  const addProfession = (profession) => {
    const trimmed = profession.trim();
    if (!trimmed || value.includes(trimmed)) return;
    onChange([...value, trimmed]);
    setQuery("");
    setIsOpen(false);
  };

  const removeProfession = (profession) => {
    onChange(value.filter((p) => p !== profession));
  };

  const handleKeyDown = (e) => {
    if (e.key === "Backspace" && query === "" && value.length > 0) {
      e.preventDefault();
      removeProfession(value[value.length - 1]);
      return;
    }
    if (e.key === "Enter") {
      e.preventDefault();
      if (query.trim()) addProfession(query.trim());
      return;
    }
    if (e.key === "ArrowDown" && suggestions.length > 0) {
      e.preventDefault();
      setIsOpen(true);
      return;
    }
  };

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (containerRef.current && !containerRef.current.contains(e.target)) {
        setIsOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  return (
    <div ref={containerRef} className="relative">
      <div
        className={`flex flex-wrap items-center gap-1.5 min-h-[44px] w-full rounded-lg border bg-green-50/50 px-3 py-2 text-sm text-gray-800 transition-colors cursor-text ${
          isOpen
            ? "border-green-500 ring-2 ring-green-500/30"
            : "border-green-200 focus:border-green-500 focus:outline-none focus:ring-2 focus:ring-green-500/30"
        }`}
        onClick={() => {
          setIsOpen(true);
        }}
      >
        {value.map((profession) => (
          <span
            key={profession}
            className="inline-flex items-center gap-1 bg-green-100 text-green-800 rounded-md px-2 py-1 text-xs font-medium"
          >
            {profession}
            <button
              type="button"
              tabIndex={-1}
              onClick={(e) => {
                e.stopPropagation();
                removeProfession(profession);
              }}
              className="ml-0.5 text-green-600 hover:text-green-900 focus:outline-none"
              aria-label={`Remove ${profession}`}
            >
              ×
            </button>
          </span>
        ))}
        <input
          type="text"
          value={query}
          onChange={(e) => {
            setQuery(e.target.value);
            setIsOpen(true);
          }}
          onFocus={() => setIsOpen(true)}
          onKeyDown={handleKeyDown}
          placeholder={value.length === 0 ? placeholder : ""}
          className="flex-1 min-w-[120px] bg-transparent outline-none placeholder-gray-400/70 text-sm py-0.5"
        />
      </div>

      {isOpen && suggestions.length > 0 && (
        <ul className="absolute z-10 mt-1 w-full max-h-52 overflow-auto rounded-lg border border-gray-200 bg-white shadow-lg py-1">
          {suggestions.map((s) => (
            <li key={s}>
              <button
                type="button"
                tabIndex={-1}
                onClick={() => addProfession(s)}
                onMouseDown={(e) => e.preventDefault()}
                className="w-full text-left px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition-colors"
              >
                {s}
              </button>
            </li>
          ))}
        </ul>
      )}

      {isOpen && query.trim() && suggestions.length === 0 && (
        <div className="absolute z-10 mt-1 w-full rounded-lg border border-gray-200 bg-white shadow-lg px-3 py-2 text-sm text-gray-400">
          No suggestions found
        </div>
      )}
    </div>
  );
}
