const mongoose = require("mongoose");

const bookingSchema = new mongoose.Schema(
  {
    clientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    providerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    repairDescription: { type: String, required: true, trim: true, maxlength: 2000 },
    address: { type: String, default: "", trim: true, maxlength: 300 },
    photoUrl: { type: String, default: "", trim: true, maxlength: 500 },
    urgency: { type: String, enum: ["Emergency", "Flexible"], default: "Flexible" },
    serviceDate: { type: Date, required: true },
    timeSlot: {
      type: String,
      enum: ["7:30 AM", "9:00 AM", "10:30 AM", "1:30 PM", "3:00 PM", "4:30 PM", "6:00 PM"],
      required: true,
    },
    offeredPrice: { type: Number, required: true, min: 100 },
    travelDistanceKm: { type: Number, min: 0 },
    travelBaseFee: { type: Number, min: 0 },
    travelFeePerKm: { type: Number, min: 0 },
    travelFee: { type: Number, min: 0, default: 0 },
    travelFeeBeforeDiscount: { type: Number, min: 0 },
    travelFeeDiscount: { type: Number, min: 0, default: 0 },
    voucherId: { type: mongoose.Schema.Types.ObjectId },
    voucherReservationId: { type: String },
    stampAwardedAt: { type: Date },
    tipAmount: { type: Number, min: 0, default: 0 },
    paymentMethod: { type: String, enum: ["cash"], default: "cash", required: true },
    cashPaidConfirmedAt: { type: Date },
    cashReceivedConfirmedAt: { type: Date },
    clientConfirmedCash: { type: Boolean, default: false },
    providerConfirmedCash: { type: Boolean, default: false },
    workCompletedAt: { type: Date },
    settledAt: { type: Date },
    cashReceipt: {
      receiptNumber: { type: String, trim: true },
      issuedAt: { type: Date },
      serviceDescription: { type: String, trim: true },
      totalAmount: { type: Number, min: 0 },
      paymentMethod: { type: String, enum: ["cash"] },
      completionNote: { type: String, trim: true, maxlength: 2000 },
      completionPhotos: { type: [String], default: [] },
      completionSubmittedAt: { type: Date },
    },
    completionNote: { type: String, default: "", trim: true, maxlength: 2000 },
    completionPhotos: { type: [String], default: [] },
    completionSubmittedAt: { type: Date },
    revisionRequests: [{
      requestedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
      note: { type: String, required: true, trim: true, maxlength: 1000 },
      photos: { type: [String], default: [] },
      status: { type: String, enum: ["open", "accepted", "disputed", "addressed"], default: "open" },
      responseNote: { type: String, default: "", trim: true, maxlength: 1000 },
      createdAt: { type: Date, default: Date.now },
      respondedAt: { type: Date },
      addressedAt: { type: Date },
    }],
    status: {
      type: String,
      enum: ["pending", "approved", "en_route", "in_progress", "complete", "in_revision", "disputed", "closed", "settled", "cancel_requested", "canceled", "declined", "expired", "Pending Request", "Confirmed", "On the Way", "In Progress", "Cancellation Requested", "Declined", "Cancelled", "Completed", "Settled"],
      default: "pending",
      index: true,
    },
    requestExpiresAt: { type: Date, default: undefined, index: true },
    cancellationReason: { type: String, default: "", trim: true, maxlength: 500 },
    cancellationRequestedBy: { type: String, enum: ["client", "provider"], default: undefined },
    cancellationRequestedAt: { type: Date },
    cancellationExpiresAt: { type: mongoose.Schema.Types.Mixed, default: null },
    cancellationPreviousStatus: { type: String, enum: ["pending", "approved", "en_route", "in_progress"] },
    cancellationResolvedAt: { type: Date },
    cancellationOutcome: { type: String, enum: ["instant", "approved", "rejected", "expired"] },
    clientRating: { type: Number, min: 1, max: 5 },
    clientReview: { type: String, default: "", trim: true, maxlength: 1000 },
    clientReviewPhotos: { type: [String], default: [] },
    reviewedAt: { type: Date },
    statusHistory: [{
      status: { type: String, enum: ["pending", "approved", "en_route", "in_progress", "complete", "in_revision", "disputed", "closed", "settled", "cancel_requested", "canceled", "declined", "expired"] },
      at: { type: Date, default: Date.now },
    }],
    adminOverrideHistory: [{
      adminEmail: { type: String, required: true, trim: true, lowercase: true },
      fromStatus: { type: String, required: true, trim: true },
      toStatus: { type: String, required: true, trim: true },
      reason: { type: String, required: true, trim: true, maxlength: 500 },
      at: { type: Date, default: Date.now },
    }],
    providerUpdates: [{
      type: { type: String, enum: ["note", "reschedule"], required: true },
      note: { type: String, required: true, trim: true, maxlength: 500 },
      proposedServiceDate: { type: Date },
      proposedTimeSlot: { type: String, enum: ["7:30 AM", "9:00 AM", "10:30 AM", "1:30 PM", "3:00 PM", "4:30 PM", "6:00 PM"] },
      status: { type: String, enum: ["sent", "pending", "accepted", "rejected"], required: true },
      requestedAt: { type: Date, default: Date.now },
      respondedAt: { type: Date },
    }],
    counterOffers: [{
      proposedBy: { type: String, enum: ["client", "provider"], required: true },
      proposedPrice: { type: Number, min: 100 },
      proposedServiceDate: { type: Date },
      proposedTimeSlot: { type: String, enum: ["7:30 AM", "9:00 AM", "10:30 AM", "1:30 PM", "3:00 PM", "4:30 PM", "6:00 PM"] },
      proposedRepairDescription: { type: String, trim: true, maxlength: 2000 },
      note: { type: String, trim: true, maxlength: 500 },
      status: { type: String, enum: ["pending", "accepted", "rejected"], default: "pending" },
      createdAt: { type: Date, default: Date.now },
      respondedAt: { type: Date },
    }],
  },
  { timestamps: true }
);

bookingSchema.index({ clientId: 1, createdAt: -1 });
bookingSchema.index({ providerId: 1, createdAt: -1 });
bookingSchema.index({ providerId: 1, serviceDate: 1, timeSlot: 1 }, { unique: true, partialFilterExpression: { status: { $in: ["pending", "approved", "en_route", "in_progress", "cancel_requested"] } } });

module.exports = mongoose.model("Booking", bookingSchema);
